### PR TITLE
Fix restoration of change addresses & remove sleep time in tests

### LINKED ISSUE #24: Restorer must restore also internal addresses
At the moment the restoreAddresses function of both xpub and mnemonic identities restores only external address.
Specifically it makes use of the [generateSetOfAddresses](https://github.com/vulpemventures/ldk/blob/f16ffb92b3d643d5e2f101190572070cf7f5f022/src/identity/masterpubkey.ts#L235) method that derives only external addresses.
This should be done also for those internal though, hence this method should be changed to expect a change boolean flag and the while loop in restoreAddresses should be done also for the internal chain.

### PR DESCRIPTION
**Pull request by altafan**
This fixes #24 and removes sleep time from tests.

Please @tiero @louisinger, review this.

### CODE REVIEW

**Comment by altafan** [comment]
This applies the same logic for restoring external (receiving) addresses also to those internal (change).

File: src/identity/masterpubkey.ts [hunk 1]
```diff
@@ -276,70 +270,60 @@ export class MasterPublicKey extends Identity implements IdentityInterface {
...
+    for (let i = 0; i < 2; i++) {
+      const change = i === 1;
+      let counter = 0;
+      let index = 0;
+
+      const usedAddresses: AddressInterfaceExtended[] = [];
+      const incrementOrResetCounter = (
+        addresses: AddressInterfaceExtended[]
+      ) => (hasBeenUsed: boolean, index: number) => {
+        if (hasBeenUsed === true) {
```
Comment (tiero) [inline src/identity/masterpubkey.ts:284]:
```suggestion
        if (hasBeenUsed) {
```

File: src/identity/masterpubkey.ts [hunk 2]
```diff
@@ -276,70 +270,60 @@ export class MasterPublicKey extends Identity implements IdentityInterface {
...
+          counter = 0;
+          usedAddresses.push(addresses[index]);
+        } else {
```
Comment (tiero) [inline src/identity/masterpubkey.ts:287]: else branching cound be dropped. We always increment the count, if we enter in the `if hasBeenUsed` then we overwrite the counter to 0 anyway
